"""added verification

Revision ID: 2a74fc746c13
Revises: 80235f5ea9d7
Create Date: 2026-05-26 05:21:42.993738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a74fc746c13'
down_revision: Union[str, Sequence[str], None] = '80235f5ea9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_accounts', sa.Column('additional_document', sa.String(length=255), nullable=True), schema='profile')
    op.add_column('seller_accounts', sa.Column('tin', sa.String(length=20), nullable=True), schema='profile')
    op.add_column('seller_accounts', sa.Column('legal_address', sa.String(length=255), nullable=True), schema='profile')
    op.add_column('seller_accounts', sa.Column('verification_status', sa.String(length=20), nullable=True), schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_accounts', 'verification_status', schema='profile')
    op.drop_column('seller_accounts', 'legal_address', schema='profile')
    op.drop_column('seller_accounts', 'tin', schema='profile')
    op.drop_column('seller_accounts', 'additional_document', schema='profile')
    # ### end Alembic commands ###
