"""added image on store

Revision ID: 30e4a30033c1
Revises: 2a74fc746c13
Create Date: 2026-05-27 09:37:08.054538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e4a30033c1'
down_revision: Union[str, Sequence[str], None] = '2a74fc746c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('image', sa.String(length=255), nullable=True), schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'image', schema='profile')
    # ### end Alembic commands ###
