"""added device_type on auc

Revision ID: 3945c2166879
Revises: 6e315c1c2969
Create Date: 2026-04-21 04:03:44.645098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3945c2166879'
down_revision: Union[str, Sequence[str], None] = '6e315c1c2969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_update_configs', sa.Column('type', sa.String(length=20), nullable=True), schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_update_configs', 'type', schema='profile')
    # ### end Alembic commands ###
