"""added adv banner

Revision ID: 6e315c1c2969
Revises: f7ae81aa086c
Create Date: 2026-04-18 05:58:19.501906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e315c1c2969'
down_revision: Union[str, Sequence[str], None] = 'f7ae81aa086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('desktop_horizontal', sa.String(length=255), nullable=True),
    sa.Column('desktop_detail', sa.String(length=255), nullable=True),
    sa.Column('mobile_horizontal', sa.String(length=255), nullable=True),
    sa.Column('mobile_detail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertising_banners', schema='profile')
    # ### end Alembic commands ###
