"""added lat, lng

Revision ID: 71dc7b4f4f42
Revises: 319458474918
Create Date: 2026-03-30 08:15:50.663040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dc7b4f4f42'
down_revision: Union[str, Sequence[str], None] = '319458474918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True), schema='profile')
    op.add_column('profiles', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True), schema='profile')
    op.create_unique_constraint(None, 'profiles', ['user_id'], schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', schema='profile', type_='unique')
    op.drop_column('profiles', 'latitude', schema='profile')
    op.drop_column('profiles', 'longitude', schema='profile')
    # ### end Alembic commands ###
