"""added social medias on store

Revision ID: 80235f5ea9d7
Revises: a9d6363b455b
Create Date: 2026-05-16 08:36:49.016669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80235f5ea9d7'
down_revision: Union[str, Sequence[str], None] = 'a9d6363b455b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('social_medias', sa.JSON(), nullable=True), schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'social_medias', schema='profile')
    # ### end Alembic commands ###
