"""set to null link

Revision ID: a9d6363b455b
Revises: 3945c2166879
Create Date: 2026-04-24 11:27:58.318123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d6363b455b'
down_revision: Union[str, Sequence[str], None] = '3945c2166879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertising_banners', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertising_banners', 'link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='profile')
    # ### end Alembic commands ###
