PROFILE_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
PROFILES_FOLDER = "profiles"

SELLER_ACCOUNT_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5 MB
SELLER_ACCOUNTS_FOLDER = "seller_accounts"

REQUIRED_PROFILE_FIELDS = ("full_name", "email", "phone")

PHONE = "phone"


ADVERTISING_BANNER_MAX_FILE_SIZE = 2 * 1024 * 1024  # 2 MB
ADVERTISING_BANNER_FOLDER = "advertising_banners"

ADVERTISING_BANNER_ALLOWED_EXTS = {".png", ".jpg"}

STORE_MAX_FILE_SIZE = 2 * 1024 * 1024  # 2 MB
STORES_FOLDER = "stores"
